"use client";

import ReactGlobe from "../globe/react-globe";
import { MaxWidthWrapper } from "../layout/max-width-wrapper";
import { useSectionInView } from "./use-section-in-view";
import {
  VerticalTimeline,
  VerticalTimelineElement,
} from "react-vertical-timeline-component";
import "react-vertical-timeline-component/style.min.css";
import { Suspense, useState } from "react";
import { Badge } from "@/components/ui/badge";

export default function Experience() {
  const { ref } = useSectionInView("Experience");

  return (
    <section className="bg-gradient-to-b from-transparent from-40% to-[#fafafa] pb-10">
      <MaxWidthWrapper>
        <div ref={ref} className="">
          <ReactGlobe></ReactGlobe>
          <div className="text-4xl font-medium pb-10 pt-10" id="experience">
            Experience
          </div>
          <div className="grid md:grid-cols-2 gap-4">
            <div className="border rounded-xl p-5 transition duration-300 hover:border-gray-400 hover:bg-white">
              <div className="font-medium text-md py-2">2022-2023</div>
              <div className="font-semibold text-2xl py-2">
                Software engineer - Kanverse.ai
              </div>
              <div className="font-medium text-md py-2">
                Intelligent document processing software. Responsible for
                integrating model deployment, testing and training features to
                the platform. Integrated new ocr solutions and developed
                document processing testing tools.
              </div>
              <div className="flex flex-wrap gap-3 pt-2">
                <Badge className="h-8 rounded-md">Nodejs</Badge>
                <Badge className="h-8 rounded-md">Tensorflow</Badge>
                <Badge className="h-8 rounded-md">Vuejs</Badge>
                <Badge className="h-8 rounded-md">Pytorch</Badge>
                <Badge className="h-8 rounded-md">Javascript</Badge>
                <Badge className="h-8 rounded-md">Python</Badge>
                <Badge className="h-8 rounded-md">Docker</Badge>
              </div>
            </div>

            <div className="border rounded-xl p-5 transition duration-300 hover:border-gray-400 hover:bg-white">
              <div className="font-medium text-md py-2">2022-2023</div>
              <div className="font-semibold text-2xl py-2">
                Software engineer intern - Cognologix (Uber)
              </div>
              <div className="font-medium text-md py-2">
                Developed a data validation library that validated 100,000
                messages and events per second generated by uber and uber eats.
              </div>
              <div className="flex flex-wrap gap-3 pt-2">
                <Badge className="h-8 rounded-md">Golang</Badge>
                <Badge className="h-8 rounded-md">Apache Kafka</Badge>
                <Badge className="h-8 rounded-md">Apache Flink</Badge>
                <Badge className="h-8 rounded-md">Apache Pinot</Badge>
              </div>
            </div>

            <div className="border rounded-xl p-5 transition duration-300 hover:border-gray-400 hover:bg-white">
              <div className="font-semibold text-2xl py-2">
                Freelance web developer
              </div>
              <div className="font-medium text-md py-2">
                Developed Full stack ecommerce websites for clients.
              </div>
              <div className="flex flex-wrap gap-3 pt-2">
                <Badge className="h-8 rounded-md">Nextjs</Badge>
                <Badge className="h-8 rounded-md">React</Badge>
                <Badge className="h-8 rounded-md">Postgresql</Badge>
                <Badge className="h-8 rounded-md">Supabase</Badge>
                <Badge className="h-8 rounded-md">Turborepo</Badge>
                <Badge className="h-8 rounded-md">Tailwind</Badge>
              </div>
            </div>
          </div>
        </div>
      </MaxWidthWrapper>
    </section>
  );
}
